title: Omar Vardi
description: Cybersecurity Specialist | GIAC Certified | U.S. Navy Veteran
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme

show_downloads: false

github: [metadata]
