title: Omar Vardi
description: Cybersecurity Specialist | GIAC Certified | U.S. Navy Veteran
url: https://vardiomar.github.io
permalink: pretty
remote_theme: daviddarnes/alembic@main

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-include-cache
  - jemoji

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page

navigation_header:
  - title: Omar Vardi
    url: /
  - title: Projects
    url: /projects/
  - title: Academic Work
    url: /academic/

social_links:
  LinkedIn: https://linkedin.com/in/omarvardi
  GitHub: https://github.com/vardiomar
